[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "glider-optimization"
version = "0.1.0"
dependencies = [
    "pyyaml",
    "pydantic",
    "numpy",
    "wandb",
    "pandas",
    "aerosandbox",
    "casadi",
    "imageio",
    "torch",
    "plotly"
]

[project.scripts]
glider-opt = "glider_optimization.main:main"

[tool.setuptools.packages.find]
where = ["."]
