from abc import ABC
from typing import Dict, Any
from glider_optimization.config import Config
import pandas as pd

class Block(ABC):
    def __init__(self, config: Config): ...
    def forward(self, downstream_info: Dict[str, Any]) -> Dict[str, Any]: ...
    def backward(self, upstream_grads: Dict[str, Any]) -> Dict[str, Any]: ...
    def resume(self, checkpoint: pd.Series): ...